version: 2
registries:
  npm-private-registry:
    type: npm-registry
    url: "${{ secrets.NPM_REGISTRY }}"
    token: "${{ secrets.NPM_TOKEN }}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 50 # only allow security update
  registries:
    - npm-private-registry