version: "3"
services:
  slack-notification:
    image: ${BUILDKITE_PLUGIN_JUNIT_SLACK_NOTIFICATION_DOCKER_CACHE}node:21
    environment:
      SLACK_TOKEN: ${TOKEN_VALUE}
      SLACK_CHANNEL: ${BUILDKITE_PLUGIN_JUNIT_SLACK_NOTIFICATION_SLACK_CHANNEL}
      BUILDKITE_BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
      BUILDKITE_BUILD_URL: ${BUILDKITE_BUILD_URL}
      BUILDKITE_PIPELINE_NAME: ${BUILDKITE_PIPELINE_NAME}
      BUILDKITE_BRANCH: ${BUILDKITE_BRANCH}
      BUILDKITE_MESSAGE: ${BUILDKITE_MESSAGE}
      BUILDKITE_COMMIT: ${BUILDKITE_COMMIT}
      BUILDKITE_BUILD_AUTHOR: ${BUILDKITE_BUILD_AUTHOR}
      NPM_REGISTRY: ${NPM_REGISTRY}
      NPM_TOKEN: ${NPM_TOKEN}
    command: /app/scripts/run.sh
    volumes:
      - $ARTIFACTS_DIR:/app/reports
      - .:/app
    working_dir: /app
    entrypoint: ["bash"]
  lint:
    image: buildkite/plugin-linter:latest
    command: ['--id', 'iress/junit-slack-notification']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester:latest
    volumes:
      - ".:/plugin:rw"
