name: Junit Slack Notification
description: Notify Slack with a summary of the Junit build
author: https://github.com/iress
main: index.js
version: 1.0
requirements:
  - docker
configuration:
  properties:
    artifacts:
      type: string
    test_suites:
      type: array
      minimum: 1
      properties:
        name:
          type: string
        artifacts:
          type: string
    SLACK_TOKEN:
      type: string
    SLACK_CHANNEL:
      type: string
    DOCKER_CACHE:
      type: string
    SLACK_TOKEN_ENV_NAME:
      type: string
  anyOf:
    - required:
        - artifacts
        - SLACK_CHANNEL
    - required:
        - test_suites
        - SLACK_CHANNEL
  additionalProperties: false
